spring.application.name=receipt-extractor
ocr.tessdata-path=src/main/resources/tessdata
ocr.languages=vie+eng
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
